# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml
  - model: mnist.yaml # very important
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null

task_name: "demo"

# checkpoint is necessary for demo
ckpt_path: ???